---
- name: Install dracut
  pacman:
    name: dracut
    state: present
  when: dracut|bool

- name: Remove mkinitcpio
  pacman:
    name: mkinitcpio
    state: absent
  when: dracut|bool

- name: Ensure /etc/pacman.d/hooks exists
  file:
    path: "/etc/pacman.d/hooks"
    owner: root
    group: root
    mode: 0755
    state: directory
  when: dracut|bool

- name: Install dracut configuration file
  copy:
    src: dracut.conf
    dest: /etc/dracut.conf.d/10-dracut.conf
    owner: root
    group: root
    mode: 0644
  when: dracut|bool

- name: Install dracut install script
  copy:
    src: dracut-install.sh
    dest: /usr/local/sbin/dracut-install.sh
    owner: root
    group: root
    mode: 0700
  when: dracut|bool

- name: Install dracut remove script
  copy:
    src: dracut-remove.sh
    dest: /usr/local/sbin/dracut-remove.sh
    owner: root
    group: root
    mode: 0700
  when: dracut|bool

- name: Install dracut pacman install hook
  copy:
    src: dracut-install.hook
    dest: /etc/pacman.d/hooks/10-dracut-install.hook
    owner: root
    group: root
    mode: 0644
  when: dracut|bool

- name: Install dracut pacman remove hook
  copy:
    src: dracut-remove.hook
    dest: /etc/pacman.d/hooks/10-dracut-remove.hook
    owner: root
    group: root
    mode: 0644
  when: dracut|bool
