---
- name: Set the system time zone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Set the hostname
  ansible.builtin.copy:
    content: "{{ inventory_hostname }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: '644'
    force: true

- name: Install hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '644'

- name: Set journald storage to volatile
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#Storage="
    line: Storage=volatile
  when: arch != "auto"
  notify: "restart systemd-journald"

- name: Remove old persistent journald logs
  ansible.builtin.file:
    path: /var/log/journal
    state: absent
  when: arch != "auto"

- name: Add dracut configuration
  ansible.builtin.include_tasks: dracut.yml

- name: Install packages
  ansible.builtin.include_tasks: packages.yml

- name: Add users and groups
  ansible.builtin.include_tasks: users-and-groups.yml

- name: Configure network
  ansible.builtin.include_tasks: network.yml

- name: Add security measures
  ansible.builtin.include_tasks: security.yml

- name: Configure system services
  ansible.builtin.include_tasks: services.yml
