---
- name: Set the system time zone
  timezone:
    name: "{{ timezone }}"

- name: Set the hostname
  copy:
    content: "{{ inventory_hostname }}"
    dest: /etc/hostname
    force: true

- name: Install hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- include_tasks: dracut.yml
- include_tasks: packages.yml
- include_tasks: users-and-groups.yml
- include_tasks: network.yml
- include_tasks: security.yml
- include_tasks: services.yml
