---
- name: Set the system time zone
  timezone:
    name: "{{ timezone }}"

- name: Set the hostname
  copy:
    content: "{{ inventory_hostname }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
    force: true

- name: Install hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: Set journald storage to volatile
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#Storage="
    line: Storage=volatile
  when: arch != "auto"
  notify: "restart systemd-journald"

- name: Remove old persistent journald logs
  file:
    path: /var/log/journal
    state: absent
  when: arch != "auto"

- include_tasks: dracut.yml
- include_tasks: packages.yml
- include_tasks: users-and-groups.yml
- include_tasks: network.yml
- include_tasks: security.yml
- include_tasks: services.yml
