---
- name: Install pacman config
  ansible.builtin.template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: '644'

- name: Ensure /etc/xdg/reflector directory exists
  ansible.builtin.file:
    path: /etc/xdg/reflector
    owner: root
    group: root
    mode: '755'
    state: directory
  when: arch == "auto"

- name: Install reflector config
  ansible.builtin.template:
    src: reflector.conf.j2
    dest: /etc/xdg/reflector/reflector.conf
    owner: root
    group: root
    mode: '644'
  when: arch == "auto"

- name: Enable reflector timer
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: true
    state: started
    daemon_reload: true
  when: arch == "auto"

- name: Create aurmake user
  ansible.builtin.user:
    name: aurmake
    state: present
    create_home: true

- name: Ensure aurmake user can use passwordless pacman
  ansible.builtin.lineinfile:
    dest: '/etc/sudoers.d/aurmake'
    line: 'aurmake ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    state: present
    owner: root
    group: root
    mode: '440'
    create: true
    validate: 'visudo -cf %s'

- name: Install packages
  community.general.pacman:
    name: '{{ packages }}'
    update_cache: true
    state: present
  when: 'packages | length > 0'

- name: Install AUR packages
  become: true
  become_user: aurmake
  aur:
    name: '{{ item }}'
  loop: '{{ packages_aur }}'
  when: 'packages_aur | length > 0'
