---
- name: Main | Install IPv4 iptables configuration
  ansible.builtin.template:
    src: iptables.rules.j2
    dest: /etc/iptables/iptables.rules
    owner: root
    group: root
    mode: '644'
  notify: 'restart iptables'

- name: Main | Install IPv6 iptables configuration
  ansible.builtin.template:
    src: ip6tables.rules.j2
    dest: /etc/iptables/ip6tables.rules
    owner: root
    group: root
    mode: '644'
  notify: 'restart ip6tables'

- name: Enable iptables service
  ansible.builtin.systemd:
    name: iptables.service
    enabled: true
    state: started
    daemon_reload: true

- name: Enable ip6tables service
  ansible.builtin.systemd:
    name: ip6tables.service
    enabled: true
    state: started
    daemon_reload: true

- name: Remove small Diffie-Hellman moduli
  ansible.builtin.shell: |
    awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.safe
    cp /etc/ssh/moduli.safe /etc/ssh/moduli
  args:
    creates: /etc/ssh/moduli.safe
  notify: 'restart sshd'

- name: Install sshd configuration override
  ansible.builtin.template:
    src: sshd_config_d.j2
    dest: /etc/ssh/sshd_config.d/10-custom.conf
    owner: root
    group: root
    mode: '644'
    validate: 'sshd -T -f %s'
  notify: 'restart sshd'

- name: Enable sshd service
  ansible.builtin.systemd:
    name: sshd.service
    enabled: true
    state: started
    daemon_reload: true
