---
- name: Restart systemd-network
  service:
    name: systemd-networkd
    state: restarted
  listen: "restart systemd-networkd"

- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
  listen: "restart systemd-resolved"

- name: Restart systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: restarted
  listen: "restart systemd-timesyncd"

- name: Restart iptables
  service:
    name: iptables
    state: restarted
  listen: "restart iptables"

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  listen: "restart sshd"
